%% Exact linearization of the Simulink model Active_Suspension_model
%
% This MATLAB script is the command line equivalent of the exact
% linearization tab in linear analysis tool with current settings.
% It produces the exact same linearization results as hitting the Linearize button.

% MATLAB(R) file generated by MATLAB(R) 9.13 and Simulink Control Design (TM) 6.2.
%
% Generated on: 29-Jun-2023 11:24:05

%--------------------------------------------------------------------------
% REMEMBER TO SAVE SYS FROM
%--------------------------------------------------------------------------

%% Specify the model name
model = 'quarter_car_Active_Suspension_model';

%% Specify the analysis I/Os
% Get the analysis I/Os from the model
io = getlinio(model);

%% Specify the operating point
% Use the model initial condition
op = operpoint(model);


%% Linearize the model
sys = linearize(model,io,op);

% for i = 1:length(sys)
%     sys(i).OutputName
% end

%% Plot the resulting linearization


% Bode plot

figure('Name','Bode plot suspension travel'); hold on
bodemag(sys(7),sys(1),sys(4))
legend('passive','LQR','PID')
title('Bode plot suspension travel')
set(findall(gcf,'type','line'),'linewidth',3)

figure('Name','Bode plot sprung mass acceleration'); hold on
bodemag(sys(8),sys(2),sys(5))
legend('passive','LQR','PID')
title('Bode plot sprung mass acceleration')
set(findall(gcf,'type','line'),'linewidth',3)

figure('Name','Bode plot sprung mass motion'); hold on
bodemag(sys(9),sys(3),sys(6))
legend('passive','LQR','PID')
title('Bode plot sprung mass motion')
set(findall(gcf,'type','line'),'linewidth',3)

%% Zero-pole map

figure('Name','Zero-pole map suspension travel'); hold on
pzplot(sys(7),sys(1),sys(4))
legend('passive','LQR','PID')
title('Zero-pole map suspension travel')
set(findall(gcf,'type','line'),'linewidth',2)
h = findobj(gca, 'type', 'line');
set(h, 'markersize', 10)
set(h, 'linewidth', 4)

figure('Name','Zero-pole map sprung mass acceleration'); hold on
pzplot(sys(8),sys(2),sys(5))
legend('passive','LQR','PID')
title('Zero-pole map sprung mass acceleration')
set(findall(gcf,'type','line'),'linewidth',2)
h = findobj(gca, 'type', 'line');
set(h, 'markersize', 10)
set(h, 'linewidth', 4)

figure('Name','Zero-pole map sprung mass motion'); hold on
pzplot(sys(9),sys(3),sys(6))
legend('passive','LQR','PID')
title('Zero-pole map sprung mass motion')
set(findall(gcf,'type','line'),'linewidth',2)
h = findobj(gca, 'type', 'line');
set(h, 'markersize', 10)
set(h, 'linewidth', 4)